### ISSUE TITLE
Movies db sample throwing error in Azure Data Factory when trying to write to Azure Blob Storage. Empty file name in file path appears to be causing the problem.

### ISSUE THREAD

**Issue by ExpoundDS** [kromerm/adfdataflowdocs#2]

**Comment by kromerm** [comment]
When writing to Azure Blob Store or ADLS from Data Flows in ADF, it is recommended to use paths, not file names. ADF will write partitioned output files of transformed data into the stated file path.

It is possible that the demo is failing for you due to an incorrectly configured Linked Service.

Can you please confirm that you can connect to your Azure Blob Store from the Linked Service that is being used in the ADF Data Flow Sink Transformation?

If you are still unable to solve the problem, please send us an email with the error messages here: adfdataflowext@microsoft.com.
